title: Patrick Barron
subtitle: and his random thoughts
author: Patrick Barron
avatar_url: /assets/img/patrickbarrn.jpg  # Should be 160x160px.
description: > # this means to ignore newlines until "twitter_username:"
  A blog about Sitecore, Technology, and Gaming.
repository: patrickbarrn/patrickbarrn.github.io

# contact
contact:
  #email: your-email@domain.com  # Comment out this line if you don't want to expose your email.
  url: https://github.com/patrickbarrn/feedback/issues/new # Uncomment this to provide a contact form url instead of an email

# social links
twitter_username: patbarron1
github_username:  patrickbarrn
rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# 
# Subscribe Feed
# 
# By default, your site generates a subscription feed (RSS/Atom) at /feed.xml
# Uncomment the next two lines to change the path.
feed:
  path: /atom.xml

# If you use a feed publisher such as Feedburner, uncomment the next line
# subscribe_rss: https://your-feedburner-url/

# Homepage
show_excerpts: true  # set to true to show excerpts on the homepage, otherwise full posts are shown

# Comments
# To enable comments, set the `enabled` field to true and supply either a Disqus short name or a Jekyll comments receiver
comments:
  enabled: false
  show_count: false
#  receiver: https://.../  # See https://haacked.com/archive/2018/06/24/comments-for-jekyll-blogs/ for more information.
#  disqus_shortname: YOUR_DISQUS_SHORTNAME

emptyArray: [] # Leave this here.

# haackbar date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
haackbar:
  date_format: "%b %-d, %Y"

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 10 # number of posts per page
page_group_size: 5 # number of pages to group by in the pagination.
paginate_path: "/archive/page/:num"
category_dir: categories

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
remote_theme: haacked/haackbar

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache